config/routes.rb
Rails.application.routes.draw do

  get 'study_pages/*path', to: 'study_pages#show'
  get 'study_pages/home'
  get 'study_pages/help'

  get 'password_resets/new'

  get 'password_resets/edit'

  root to: 'static_pages#home'
  get 'fetch/index'
  match '/fetch',   to: 'fetch#index', via: 'get'
  get 'static_pages/home'
  get 'static_pages/nikkei'
  get 'static_pages/dow'
  get 'static_pages/shanghai'
  get 'static_pages/europe'
  get 'static_pages/bitcoin'
  get 'static_pages/commodity'
  get 'static_pages/adr'
  get 'static_pages/fx'
  get 'static_pages/portfolio'
  get 'static_pages/kessan'

  get 'static_pages/detail_adr', :as => 'detail_adr'

  get 'priceseries/new'
  get 'signup' => 'users#new'
  get 'rank/index'
  get 'adr/index'
  get 'price_newest/index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts

  resources :feeds
  resources :price_newest

end

app/controllers/static_pages_controller.rb
# モデル構造：最新断面(Pricenewest)と時系列データ(Priceseries)の二つ取得
# >ActiveRecord::Base.connection.tables


# デザイン
# http://w-finder.com/cool
# http://photoshopvip.net/archives/17887

# リアルタイム機能
# http://blog.mlkcca.com/backend/milkcocoa-for-ror/


# historical currency data取得
# http://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance?rq=1
# http://stackoverflow.com/questions/28918968/how-to-get-historical-data-for-currency-exchange-rates-via-yahoo-finance

#require 'yahoo-finance'

# nikkeiから値上がり率ランキング取得
require 'open-uri'# URLアクセス
require 'kconv'    # 文字コード変換
require 'nokogiri' # スクレイピング
require 'time'
require 'date'


# for btitcoin
require 'net/http'
require 'uri'
require 'json'

class StaticPagesController < ApplicationController

  # 以下各ページに限定したニュースフィードだけでいいかも。
  # feedsモデルにカテゴリを追加→とりあえず最初はすべてのニュースで良い
  def nikkei
    @indicated_ticker = params[:ticker]

    if @indicated_ticker
      p "params : #{@indicated_ticker}を受け取りました"
    else
      @indicated_ticker = "0000"
      #一日騰落率ランキング
      @up_ranks = get_rank_from_db("priceup")
      @down_ranks = get_rank_from_db("pricedown")
    end
    p "indicated_ticker=#{@indicated_ticker}"
    @rank_others = Rank.where(market: Rank.pluck(:market).uniq).where.not(market: "0000").where.not(name: "bitcoin")#^N225以外
    @nikkei225_now2 = Priceseries.where(ticker: @indicated_ticker).order(ymd: :desc).limit(2)
    p "nikkei225 = #{@nikkei225_now2.first.close}"
    gon.historical_data=Priceseries.where(ticker: @indicated_ticker).order(ymd: :asc)

    if @nikkei225_now2.length == 2
      todayVal = @nikkei225_now2[0].close.to_f
      yesterdayVal = @nikkei225_now2[1].close.to_f
      @returnNikkei225 = sprintf("%.2f", ((todayVal / yesterdayVal - 1.0)*100.0).to_f).to_s + "%"
      @diffNikkei225 = sprintf("%.2f", (todayVal - yesterdayVal))
      @valueNikkei225 = todayVal
    end

  end

  def dow
    # b = 13754.4566
    # print number_with_delimiter(b, :delimiter => ',')

    # candle chartはascで表示しないと正しく表示されない
    gon.historical_data=#Priceseries.all.order(:ymd)
    Priceseries.where(ticker: "^DJI").order(ymd: :asc)
    # Priceseries.find_by_sql("select * from priceseries where ticker = '^DJI' order by 'ymd' desc")

    @dow_now2 =
    Priceseries.where(ticker: "^DJI").order(ymd: :desc).limit(2)
    # Priceseries.find_by_sql("select * from Priceseries where ticker = '^DJI' order by ymd desc limit 2")

    p @dow_now2[0].close.to_f
    p @dow_now2[1].close.to_f
    if @dow_now2.length == 2
      @valuedow = @dow_now2[0].close.to_f
      yesterdayVal = @dow_now2[1].close.to_f
      @returndow = sprintf("%.2f", ((@valuedow / yesterdayVal - 1.0)*100.0).to_f).to_s + "%"
      @diffdow = sprintf("%.2f", (@valuedow - yesterdayVal))
    end

    gon.historical_tickers = [
      "VZ",#verizon
      "T",#AT&T
      "PG",#procter & gamble
      "JNJ",#johnson and johnson
      "PM",#Philip Morris International
      "BTI",#British American Tobacco
      "XOM",#エクソンモービル
      "KO",#コカコーラ
      "IBM",
      "MCD"];


    gon.historical_labels = ["verizon","t", "pg", "jnj", "pm", "bti", "xom", "ko", "ibm", "mcd"]
    gon.historical_names = ["Verizon Communications", "AT&T", "Procter&Gamble", "Johnson&johnson",
    "Philip Morris International", "British American Tabacco", "Exxon Mobil", "Coca Cola", "IBM", "Mcdonald's Corp"]
    gon.historical = {};#時系列データを格納
    gon.historical_tickers.each do |ticker|
      gon.historical[ticker] = Priceseries.where(ticker: ticker).order(ymd: :asc)
    end
    @historical_tickers = gon.historical_tickers
    @historical_labels = gon.historical_labels

  end

  def shanghai

    gon.shanghai_historical=#Priceseries.all.order(:ymd)
    Priceseries.where(ticker: "0823").order(ymd: :asc)
    # Priceseries.where(ticker: "000001.SS").order(ymd: :asc)
    # Priceseries.find_by_sql("select * from priceseries where ticker = '000001.SS' order by 'ymd' desc")

    @shanghai_now2 =
    Priceseries.where(ticker: "0823").order(ymd: :desc).limit(2)
    #Priceseries.find_by_sql("select * from Priceseries where ticker = '000001.SS' order by ymd desc limit 2")
    # Priceseries.where(ticker: "000001.SS").order(ymd: :asc).limit(2)

    p "shanghai"
    p @shanghai_now2[0].close.to_f
    p @shanghai_now2[1].close.to_f
    if @shanghai_now2.length == 2
      @valueShanghai = @shanghai_now2[0].close.to_f
      yesterdayVal = @shanghai_now2[1].close.to_f
      @returnShanghai = sprintf("%.2f", ((@valueShanghai / yesterdayVal - 1.0)*100.0).to_f).to_s + "%"
      @diffShanghai = sprintf("%.2f", (@valueShanghai - yesterdayVal))
    end


    # p "shanghai_historical = #{gon.shanghai_historical.length}"
    # gon.shanghai_historical.each do |sh|
    #   p sh
    # end



    # http://nikkei225jp.com/china/
    # 中国上海アジア市場のスクレイピング
    @arrIndices =
    ["上海総合指数 中国",
     "CSI300指数 中国",
     "上海Ｂ株 中国",
     "深センＢ株 中国",
     "上海Ａ株 中国",
     "深センＡ株 中国",
     "HangSeng 香港",
     "H株指数 香港",
     "レッドチップ指数 香港",
     "韓国",
     "加権 台湾",
     "為替 ドル円",
     "為替 ドル元",
     "ユーロ元"]
     arrIndexTickers =
     ["000001.SS",#上海総合指数 中国
      "000300.SS",#CSI300指数 中国
      "000003.SS",#上海Ｂ株 中国
      "399108.SZ",#深センＢ株 中国
      "000002.SS",#上海Ａ株 中国
      "399107.SZ",#深センＡ株 中国
      "^HIS",#HangSeng 香港
      "^HSCE",#H株指数 香港
      "^HSCC",#レッドチップ
      "^KS11",#韓国
      "^TWII",#台湾
      "USDJPY=X",#ドル円
      "USDCNY=X",#ドル元
      "EURCNY=X"#ユーロ元
    ]
    # 二つの配列からhashを作成する
    ary = [arrIndexTickers,@arrIndices].transpose
    @hash_key_name_asia = Hash[*ary.flatten]
    arrActiveRecord =  PriceNewest.where(ticker: arrIndexTickers).order(datetrade: :desc)
    # p "count = " + arrActiveRecord.count.to_s + "," + @arrIndices.count.to_s
    # @asia_newest_dataをarrIndicese(arrIndexTickers)と同じ並び順でデータを格納する
    @asia_newest_data = []
    arrIndexTickers.each do |ticker|
      # p ticker
      arrActiveRecord.each do |record|
        if record.ticker == ticker
          @asia_newest_data.push(record)
          # p @asia_newest_data.last.ticker
          break
        end
      end
    end
    # example
    # p "newest = " + @asia_newest_data[0].ticker.to_s
    # p "newest = " + @asia_newest_data[0].pricetrade.to_s
    # p "newest = " + @asia_newest_data[0].previoustrade.to_s
    # p "newest = " + @asia_newest_data[1].ticker.to_s

    cnt = 0
    @asia_newest_data.each do |asia|
      p asia.ticker.to_s + "(" + asia.pricetrade.to_s + ")" +asia.datetrade.to_s +
        @arrIndices[cnt]
      cnt = cnt + 1
    end
  end

  def europe
    gon.europe_historical=#Priceseries.all.order(:ymd)
    Priceseries.where(ticker: "^STOXX50E").order(ymd: :asc)
    # Priceseries.find_by_sql("select * from priceseries where ticker = '^FTSE' order by 'ymd' desc")
    @europe_now2 =
    Priceseries.where(ticker: "^STOXX50E").order(ymd: :desc).limit(2)
    # Priceseries.find_by_sql("select * from Priceseries where ticker = '^FTSE' order by ymd desc limit 2")
    p "shanghai"
    p @europe_now2[0].close.to_f
    p @europe_now2[1].close.to_f
    if @europe_now2.length == 2
      @valueEurope = @europe_now2[0].close.to_f
      yesterdayVal = @europe_now2[1].close.to_f
      @returnEurope = sprintf("%.2f", ((@valueEurope / yesterdayVal - 1.0)*100.0).to_f).to_s + "%"
      @diffEurope = sprintf("%.2f", (@valueEurope - yesterdayVal))
    end

    gon.historical_tickers = ["EWQ", "^FTSE?P=FTSE", "^GDAXI", "EWI"];
    gon.historical_labels = ["france", "london", "german", "italia"];
    gon.historical_names = ["フランス証券取引所", "ロンドン証券取引所", "ドイツ証券取引所", "イタリア証券取引所"];
    gon.historical = {};#時系列データを格納
    gon.historical_tickers.each do |ticker|
      gon.historical[ticker] = Priceseries.where(ticker: ticker).order(ymd: :asc)
    end
    @historical_tickers = gon.historical_tickers
    @historical_labels = gon.historical_labels


  end
  def commodity

  end
  def bitcoin
    # bitcoinに限定したニュースだけでいいかも


    # http://bitcoin.stackexchange.com/questions/32558/api-feed-for-ohlc-vwap-data-in-close-to-real-time
    gon.historical_btc =
    Priceseries.where(ticker: "btci").order(ymd: :asc)
    # Priceseries.find_by_sql("select * from priceseries where ticker = 'btci' order by 'ymd' desc")

    @btc_now2 =
    Priceseries.where(ticker: "btci").order(ymd: :desc).limit(2)
    # Priceseries.find_by_sql("select * from Priceseries where ticker = 'btci' order by ymd desc limit 2")
    if @btc_now2.length == 2
      @valueBtc = @btc_now2[0].close.to_f
      yesterdayVal = @btc_now2[1].close.to_f
      @returnBtc = sprintf("%.2f", ((@valueBtc / yesterdayVal - 1.0)*100.0).to_f).to_s + "%"
      @diffBtc = sprintf("%.2f", (@valueBtc - yesterdayVal))
    end




    # 難易度などのテーブル取得
    # http://bitcoincharts.com/markets/coinbaseUSD.html

    url = "https://bitcoincharts.com/markets/coinbaseUSD.html"
    # html = open(url) do |f|
    #   f.read # htmlを読み込んで変数htmlに渡す
    # end
    # doc = Nokogiri::HTML.parse(html.toutf8, nil, 'utf-8')
    doc = getDocFromHtml(url)
    p doc
    rank_all = Hash.new
    p "start"
    @hash_fundamentals = Hash.new
    doc.xpath('//body[@class=""]/div[@id="header"]/div[@class="container_12"]')
      .xpath('div[@class="networkinfo grid_8 right"]').children.each do |content|

      if content.xpath('table/tr').count > 0
        content.xpath('table/tr').each do |row|
          key = row.xpath('td')[0].inner_html
          value = row.xpath('td')[1].inner_html
          @hash_fundamentals[key] = value
        end
      end
    end

    @bitcoinNews = Feed.tagged_with("bitcoin")

    # 本番データに入れる時にはFeedsモデルに格納する(keyは臨機応変に修正)
    # p @bitcoinNews


  end

  def adr
    @hash_adr = {
      :SNE => "6758.T",
      :CAJ => "7751.T",
      :ATE => "6857.T",
      :NJ  => "6594.T",
      :KYO => "6971.T",
      # :KNM => "",
      :TM  => "4704.T",
      :HMC => "7267.T",
      :NTT => "9432.T",
      :DCM => "9437.T",
      # :IIJI=> "",
      # :UBIC=> "",
      # :MFJ => "",
      :MTU => "8306.T",
      :SMFG=> "8316.T",
      :NMR => "8604.T",
      :IX  => "8591.T"}

    # adr一覧を取得する

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/adr.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11 col-md-offset-1 col-lg-offset-1">
  <h1>
  ADR銘柄
  </h1>

  </div>
</div>
<br>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
    <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11 col-md-offset-1 col-lg-offset-1">
      <%= link_to "ADR(米国預託証券)とは？→説明ページへGO!", detail_adr_url %><br>
      米国の銀行に預けられている(日本企業の)株式を担保につくられた証券のこと。
      <br>この証券は元の株式と同じような値動きをするため、米国の投資家はドルでこの証券を売買でき、
      自国の通貨で日本などの海外の証券に直接投資できるメリットがある。

      <br>
      <h2>
        主な銘柄
      </h2>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <% num = 0 %>
          <% @adr_all.each do |adr| %>
            <!-- adr銘柄が主な銘柄リスト@hash_adrに存在していれば -->
            <% if @hash_adr[adr.ticker.to_sym] %>
              <% num = num + 1 %>
              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">
                <div class="row">
                  <%= num %>
                  <%= "#{adr.name}(#{adr.tcode}, #{adr.ticker})" %>
                </div>
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">
                    <%= link_to "" do %>
                      ADR
                      <!-- 90, 120 -->
                      <%= image_tag("http://ichart.finance.yahoo.com/t?s=#{adr.ticker}",
                       alt: adr.tcode, :width => '192', :height => '96') %>
                      <br>
                    <% end %>
                  </div>
                  <!-- 相対するADR銘柄 -->
                  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">
                    <%= link_to "" do %>
                      東証
                      <!-- 90, 120 -->
                      <%= image_tag("http://gchart.yahoo.co.jp/t?s=#{@hash_adr[adr.ticker.to_sym]}",
                       alt: adr.tcode, :width => '192', :height => '96') %>
                      <br>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11 col-md-offset-1 col-lg-offset-1">
          <h2>
            その他の銘柄
          </h2>
          <% @adr_all.each do |adr| %>
            <% if !@hash_adr[adr.ticker.to_sym] %>
              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">
                <div class="row">
                  <%= "#{adr.name}(#{adr.tcode}, #{adr.ticker})" %>
                </div>
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">

                    <%= link_to "" do %>
                      ADR
                      <!-- 90, 120 -->
                      <%= image_tag("http://ichart.finance.yahoo.com/t?s=#{adr.ticker}",
                       alt: adr.tcode, :width => '192', :height => '96') %>
                      <br>

                    <% end %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="border: 0.5px solid #009000">
                    <%= link_to "" do %>
                      東証
                      <!-- 90, 120 -->
                      <%= image_tag("http://gchart.yahoo.co.jp/t?s=#{adr.tcode}.T",
                       alt: adr.tcode, :width => '192', :height => '96') %>
                      <br>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

app/views/static_pages/bitcoin.html.erb
<%= include_gon %>


<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>


<script>
$(function() {
      var historicals=gon.historical_btc
      var ohlc = [],
          volume = [];
      for (i = 0; i<historicals.length; i++) {
          var unixtime1 = historicals[i]["ymd"]*1000
          var open=historicals[i]["open"];
          var high=historicals[i]["high"];
          var low=historicals[i]["low"];
          var close=historicals[i]["close"];
          var volume1=historicals[i]["volume"];
          // console.log("ymd=",data[i][0]);
          // console.log("ymd2=", unixtime1);
          ohlc.push([unixtime1,open,high,low,close]);
          volume.push([unixtime1,volume1])
      }

      // set the allowed units for data grouping
      var groupingUnits = [[
          'week',                         // unit name
          [1]                             // allowed multiples
      ], [
          'month',
          [1, 2, 3, 4, 6]
      ]];

      // create the chart
      $('#btc_historical').highcharts('StockChart', {
          rangeSelector: {
              selected: 1
          },
          title: {
              text: historicals[0]["name"] + " Price(USD)"//gon.user_name//arrayData[0]//gon.user_name
              // text: array[0]["20151230"]//gon.@pseries.
          },
          yAxis: [{
              title: {
                  text: 'price(usd)'
              },
              height: 170,
              lineWidth: 2
          }, {
              title: {
                  text: 'Volume'
              },
              top: 250,
              height: 40,
              offset: 0,
              lineWidth: 2
          }],

          series: [{
              type:'candlestick', // dowはohlcデータ取得できなかったため折れ線
              name: historicals[0].name,
              data: ohlc,
              dataGrouping: {
                  units: groupingUnits
              }
          }, {
              type: 'column',
              name: 'Volume',
              data: volume,
              yAxis: 1,
              dataGrouping: {
                  units: groupingUnits
              }
          }]
      });
    // });
});

</script>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
    <div id = "deepredBack">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-md-offset-1 col-lg-offset-1">
              <br>
              ビットコインインデックス
              <div id="nikkeiValue">
                <%= number_with_delimiter(@valueBtc.to_d.floor(2), :delimiter => ',') %>

              </div>
              <% kigo = "+" %>
              <% if @diffBtc.to_f < 0 %>
                <% kigo = "▲" %>
              <% end %>

              <div class="right">

                <%= "前日比: " + kigo + @diffBtc.to_f.abs.to_s %>
                <%= "( " + kigo + @returnBtc.to_f.abs.to_s + " % )" %>
              </div>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>

    <br>

<!-- グラフ -->
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
        <div id="btc_historical" style="width:100%; height:400px;"></div>
        <br>
      </div>
    </div>


    <br>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
        <junre_title id="sample03"> 関連ニュース </junre_title>

        <% @bitcoinNews.each do |news| %>
          <% if news %>
            <%= link_to news.title, news.link %>
            <br>
          <% end %>

        <% end %>

      </div>
    </div>

    <br>
<!-- 基本情報 -->
    <% if @hash_fundamentals %>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
          <table>
            <tr>
              <% @hash_fundamentals.keys.each do |key| %>
                <th><%= key %></th>
              <% end %>
            </tr>
            <tr>
              <% @hash_fundamentals.values.each do |fundamental| %>
                <td><%= fundamental %></td>
              <% end %>
            </tr>
          </table>
        </div>
      </div>
    <% end %>
    <br>
    <% arrGraphs = [
      "http://bitcoincharts.com/charts/coinbaseUSD/orderbook.png",
      "http://bitcoincharts.com/charts/coinbaseUSD/orderbook0.02.png",
      "http://bitcoincharts.com/charts/coinbaseUSD/accumulated_orderbook.png",
      "http://bitcoincharts.com/charts/coinbaseUSD/accumulated_orderbook0.02.png"
    ] %>
    <% arrGraphs2 = [
      "http://bitcoin.sipa.be/speed-lin-ever.png",
      "http://bitcoin.sipa.be/speed-lin.png",
      "http://bitcoin.sipa.be/speed-lin-10k.png",
      "http://bitcoin.sipa.be/speed-lin-2k.png",
      "http://bitcoin.sipa.be/speed-ever.png",
      "http://bitcoin.sipa.be/speed.png",
      "http://bitcoin.sipa.be/work.png",
      "http://bitcoin.sipa.be/growth.png",
      "http://bitcoin.sipa.be/growth-10k.png"
    ] %>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
        <junre_title id="sample03"> market depth </junre_title>
      </div>
    </div>
    <% arrGraphs.each do |graph_url| %>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
          <%= image_tag(graph_url,
           alt: "orderbook", :width => '100%', :height => '100%') %>
        </div>
      </div>
    <% end %>
    <div class="row">
      <% arrGraphs2.each_slice(2) do |arr_graph_url2| %>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 col-md-offset-1 col-lg-offset-1">
          <%= image_tag(arr_graph_url2[0],
          alt: "analysis", :width=>'100%', :height => '100%') %>
        </div>
        <% if arr_graph_url2[1] %>
          <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
            <%= image_tag(arr_graph_url2[1],
            alt: "analysis", :width=>'100%', :height => '100%') %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

app/views/static_pages/commodity.html.erb
<% chart_common_url = "http://ichart.finance.yahoo.com/t?s=" %>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
    <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11 col-md-offset-1 col-lg-offset-1">

      <h1>
        商品(コモディティ)
      </h1>

      <br><br>
      <junre_title id="sample03"> 資源 </junre_title>

        <% metals_name = "金", "銀", "銅", "白金", "パラジウム" %>
        <% metals = [ "GLD", "SLV", "CPER", "PPLT", "PALL"] %>
        <% noArray = 0 %>
        <% metals.each do |metal| %>
          <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <%= link_to "" do %>
              <!-- 90, 120 -->
              <%= image_tag("#{chart_common_url}#{metal}",
               alt: metals_name[noArray], :width => '192', :height => '96') %>
              <br>
              <%= metals_name[noArray] %>
              <% noArray = noArray + 1 %>
            <% end %>
          </div>
        <% end %>

      <br><br>
      <junre_title id="sample03"> 穀物 </junre_title>
      <% grains = ["corn", "soyb", "sgg"]
       grains_name = ["とうもろこし", "大豆", "粗糖"] %>

      <% noArray = 0 %>
      <% grains.each do |grain| %>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <%= link_to "" do %>
            <%= image_tag("#{chart_common_url}#{grain}",
            alt: grains_name[noArray], :width => '192', :height => '96') %>
            <br>
            <%= grains_name[noArray] %>
            <% noArray = noArray  + 1 %>
          <% end %>
        </div>
      <% end %>

      <br><br>
      <junre_title id="sample03"> エネルギー </junre_title>
      <% energies = ["wti", "uco", "uso"]
         energies_name = ["WTI原油", "UCO", "USO"] %>
      <% noArray = 0 %>
      <% energies.each do |energy| %>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <%= link_to "" do %>
            <%= image_tag("#{chart_common_url}#{energy}",
            alt: energies_name[noArray], :widht => '192', :height => '96') %>
            <br>
            <%= energies_name[noArray] %>
            <% noArray = noArray + 1 %>
          <% end %>
        </div>
      <% end %>
      <br>
      <%= link_to '参考', 'http://www.investopedia.com/articles/investing/102314/understanding-benchmark-oils-brent-blend-wti-and-dubai.asp' %>
    </div>

    <br><br>
    <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11 col-md-offset-1 col-lg-offset-1">
      oil
      WTI（ウエスト・テキサス・インターミディエート）
      Brent Blend(北海ブレント)
      Dubai(ドバイ原油)
      上記２指数についてはyahooでは取得できないようなので以下を使用？
      UCO -> http://finance.yahoo.com/q?s=UCO
      USO -> http://finance.yahoo.com/q?s=USO
      <br>
      東京工業取引所
      http://www8.cao.go.jp/kisei-kaikaku/kaigi/meeting/2013/wg/sogyo/130425/item1-2.pdf
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

app/views/static_pages/portfolio.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
    potfolio

  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <%= render 'layouts/sidebar' %>
  </div>
</div>